### ISSUE TITLE
fatal: [XXXX-root-node0]: FAILED! => {"msg": "'list object' has no attribute 'packages'. 'list object' has no attribute 'packages'"}

### ISSUE THREAD

**Issue by jobinau** [ihanick/anydbver#30]
```
# anydbver --version
anydbver version
Version: 0.1.13
```
## Step to reproduce
```
 anydbver --namespace=XXXX deploy os:jammy pg:16
```

**Comment by ihanick** [comment]
This particular issue is fixed with v0.1.15:
https://github.com/ihanick/anydbver/releases/tag/v0.1.15

Before this release there is no implementation for PGDG installations on jammy.

The release allows to install postgresql packages from archive PGDG repository.

In future I'm going to check more complex configurations (not just a package installation) and add support for other debian-based distributions, supported by PGDG. Also anydbver needs a support for non-archive repository for latest versions.
